name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    
jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run nix checks
        run: nix flake check .
      - name: Run non derivation checks
        run : nix run .#ci-all